pipeline:
  identifier: Build_testRepository_1732096559579
  name: Build testRepository
  orgIdentifier: default
  projectIdentifier: TestProject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.GitHub
        repoName: testRepository
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec:
              selectors:
                - docker-delegate
            type: Docker
        type: CI
